# Generated by Django 3.1.7 on 2021-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_fit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloricdemand',
            name='calories',
            field=models.IntegerField(default=1800),
        ),
        migrations.AlterField(
            model_name='caloricdemand',
            name='carbohydrates',
            field=models.IntegerField(default=225),
        ),
        migrations.AlterField(
            model_name='caloricdemand',
            name='fat',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='caloricdemand',
            name='protein',
            field=models.IntegerField(default=135),
        ),
    ]
